# Generated by Django 4.0.2 on 2022-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('categories', models.CharField(choices=[('Development', 'Development'), ('Startup', 'Startup'), ('News', 'News')], max_length=150)),
                ('content', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='posts.Tag')),
            ],
        ),
    ]
